// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	campaigns "gosqlmockdemo/definitions/campaigns"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetCampaigns provides a mock function with given fields: f
func (_m *Service) GetCampaigns(f campaigns.ListFilter) ([]campaigns.Campaign, error) {
	ret := _m.Called(f)

	var r0 []campaigns.Campaign
	if rf, ok := ret.Get(0).(func(campaigns.ListFilter) []campaigns.Campaign); ok {
		r0 = rf(f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]campaigns.Campaign)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(campaigns.ListFilter) error); ok {
		r1 = rf(f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
